{% set name = "MAPIT" %}
{% set version = "1.5.0b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sandialabs/MAPIT/archive/{{ version }}.tar.gz
  sha256: 58867341071d8e3cbf52cfe5e6c5ab843a5c4b4eace3e9b7f7969d9c4d70eb38

build:
  entry_points:
    - MAPIT = MAPIT.GUI.MAPIT_main:launchMAPIT
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - pillow
    - tqdm
    - scipy
    - pyside6
    - ray-default

test:
  imports:
    - MAPIT
  commands:
    - pip check
  requires: 
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/sandialabs/MAPIT
  summary: Python package designed to aid in safeguards analysis of bulk materials
  license: GPL-3.0-only
  license_file:
    - LICENSE.md
    - NOTICE.md

extra:
  recipe-maintainers:
    - nshoman
