{% set name = "MAPIT" %}
{% set version = "1.5.10b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sandialabs/MAPIT/archive/{{ version }}.tar.gz
  sha256: 6d2925f459d02f1880823ab7aa15f0e74e899713abda76eaadce743096de3775

build:
  entry_points:
    - MAPIT = MAPIT.GUI.MAPIT_main:launchMAPIT
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - pillow
    - tqdm
    - scipy
    - pyside6
    - alive_progress
    - yaspin

test:
  imports:
    - MAPIT
  commands:
    - pip check
  requires: 
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/sandialabs/MAPIT
  summary: Python package designed to aid in safeguards analysis of bulk materials
  license: GPL-3.0-only
  license_file:
    - LICENSE.md
    - NOTICE.md

extra:
  recipe-maintainers:
    - nshoman
